kind: pipeline
name: default

steps:
- name: build
  image: registry.gitlab.com/centerorbit/brother-wp-sdk
  commands:
    - entrypoint build
    - entrypoint package

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: builds/**/*.zip
  when:
    event: tag